from .health import analyze_health_history
from .calves import calculate_weaned_calves_ratio, analyze_weaning_time
from .vaccines import calculate_vaccine_coverage
from .weight import analyze_weight_variation, analyze_weight_variation_month
